import {useEffect,useState} from 'react';
import {dataService,isDemo} from '../../services';
import {siteConfig} from '../../data/siteConfig';

const calendarTitle='Baby Shower — Jéssica & David';
const compactDate=value=>value.replaceAll('-','').replaceAll(':','');
const calendarDates=()=>`${compactDate(siteConfig.eventDate)}T${compactDate(siteConfig.eventTime)}00/${compactDate(siteConfig.eventDate)}T${compactDate(siteConfig.eventEndTime)}00`;
const googleCalendarUrl=()=>{const params=new URLSearchParams({action:'TEMPLATE',text:calendarTitle,dates:calendarDates(),ctz:'Europe/Lisbon',details:'Vamos celebrar juntos esta nova aventura. Baby shower de Jéssica e David.',location:`${siteConfig.venueName}, ${siteConfig.address}`});return `https://calendar.google.com/calendar/render?${params}`};
const downloadCalendar=()=>{const start=`${compactDate(siteConfig.eventDate)}T${compactDate(siteConfig.eventTime)}00`,end=`${compactDate(siteConfig.eventDate)}T${compactDate(siteConfig.eventEndTime)}00`,stamp=new Date().toISOString().replaceAll('-','').replaceAll(':','').replace(/\.\d{3}/,'');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//DevRoots//Baby Shower//PT','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:baby-shower-jessica-david-${siteConfig.eventDate}@devroots`,`DTSTAMP:${stamp}`,`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${calendarTitle}`,`DESCRIPTION:Vamos celebrar juntos esta nova aventura.`,`LOCATION:${siteConfig.venueName}\, ${siteConfig.address.replaceAll(',','\\,')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));link.download='baby-shower-jessica-david.ics';link.click();URL.revokeObjectURL(link.href)};

export default function RSVPForm(){
  const emptyForm={guestListId:'',fullName:'',adults:1,children:0,status:'yes',message:''};
  const [form,setForm]=useState(emptyForm);
  const [invitations,setInvitations]=useState([]);
  const [otherName,setOtherName]=useState(false);
  const [state,setState]=useState('');
  useEffect(()=>{dataService.getGuests?.().then(rows=>{const pinned='Inês (tia babada)';setInvitations([...rows].sort((a,b)=>a.name===pinned?-1:b.name===pinned?1:a.name.localeCompare(b.name,'pt-PT',{sensitivity:'base'})))})},[]);
  const chooseInvitation=e=>{const id=e.target.value;if(id==='other'){setOtherName(true);setForm({...form,guestListId:'',fullName:''});return}const invitation=invitations.find(x=>x.id===id);setOtherName(false);setForm({...form,guestListId:id,fullName:invitation?.name||''})};
  const submit=async e=>{e.preventDefault();if(!form.fullName.trim()){setState('Seleciona o teu convite ou indica o teu nome.');return}if(Number(form.adults)+Number(form.children)<1){setState('Indica pelo menos uma pessoa.');return}setState('loading');try{await dataService.addRsvp({...form,fullName:form.fullName.trim()});setState(form.status==='yes'?'success':'declined');setForm(emptyForm);setOtherName(false)}catch{setState('Não foi possível enviar. Tenta novamente.')}};
  return <form className="rsvp-form" onSubmit={submit}>
    {invitations.length?<><div className="field"><label htmlFor="invitation">O teu convite</label><select id="invitation" value={otherName?'other':form.guestListId} onChange={chooseInvitation} required><option value="">Seleciona o nome ou família…</option>{invitations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}<option value="other">Não encontro o meu nome</option></select><small className="field-help">Selecionar o convite permite atualizar automaticamente a resposta na lista.</small></div>{otherName&&<div className="field"><label htmlFor="name">Nome</label><input id="name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} autoComplete="name" required/></div>}</>:<div className="field"><label htmlFor="name">Nome</label><input id="name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} autoComplete="name" required/></div>}
    <div className="guest-counts"><div className="field"><label htmlFor="adults">Número de adultos</label><input id="adults" type="number" min="0" max="20" value={form.adults} onChange={e=>setForm({...form,adults:e.target.value})} required/></div><div className="field"><label htmlFor="children">Número de crianças</label><input id="children" type="number" min="0" max="20" value={form.children} onChange={e=>setForm({...form,children:e.target.value})} required/></div></div>
    <fieldset><legend>Confirmação</legend><div className="attendance-options"><label className="radio"><input type="radio" name="status" checked={form.status==='yes'} onChange={()=>setForm({...form,status:'yes'})}/> Vou estar presente</label><label className="radio"><input type="radio" name="status" checked={form.status==='no'} onChange={()=>setForm({...form,status:'no'})}/> Não vou conseguir</label></div></fieldset>
    <div className="field"><label htmlFor="message">Mensagem <span>(opcional)</span></label><textarea id="message" rows="3" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></div>
    {isDemo&&<p className="demo-note">Modo de demonstração — estes dados ficam apenas neste dispositivo.</p>}
    {state==='success'?<div className="rsvp-success" role="status"><p className="success">Presença confirmada. Obrigado por fazeres parte deste momento!</p><div className="calendar-box"><strong>Guarda o dia no teu calendário</strong><p>Baby Shower — Jéssica &amp; David · 16 de outubro, 14:30</p><div className="calendar-actions"><a className="btn calendar-google" href={googleCalendarUrl()} target="_blank" rel="noreferrer">Adicionar ao Google Calendar</a><button type="button" className="btn" onClick={downloadCalendar}>Apple Calendar / iCloud (.ics)</button></div></div></div>:state==='declined'?<p className="success" role="status">Resposta registada. Obrigado por nos avisares.</p>:state&&state!=='loading'?<p className="error" role="alert">{state}</p>:null}
    <button className="btn primary full" disabled={state==='loading'}>{state==='loading'?'A enviar…':'Enviar confirmação'}</button>
  </form>
}
